#!/usr/bin/env python3
"""LeviScript auto-binding generator.

This is the "auto binding program": it reads a declarative JSON specification of
native C++ classes / functions and emits C++ source that registers them into a
`ls::script::ScriptEngine` through the inheritance-capable ClassBinder.

It exists so that binding hundreds of Minecraft / LeviLamina symbols is a matter
of describing them in JSON (which can itself be produced from headers) instead of
hand-writing glue. The generated code uses exactly the same API as the hand
written sample in src/native/api/McApi.cpp.

Usage:
    python autobind.py spec.json -o GeneratedApi.cpp
    python autobind.py spec.json -o GeneratedApi.cpp --emit-expected expected_api.json

Spec format (see spec/mc_sample.json for a complete example):
{
  "namespace": "mc",                     # script global that will hold the API
  "functionName": "bindGeneratedMcApi",  # emitted C++ function name
  "includes": ["mc/Player.h"],           # extra #include lines
  "classes": [
    {
      "scriptName": "Player",
      "cppType": "::mc::Player",
      "base": "LivingEntity",            # scriptName of the base class or null
      "constructible": true,             # emit `new ScriptName()` support
      "constructor": null,               # optional custom factory expression
      "methods":  [{"scriptName": "kick", "cpp": "&::mc::Player::kick"}],
      "properties":[{"scriptName":"uuid","get":"&::mc::Player::uuid","set":null}],
      "staticMethods":[{"scriptName":"create","cpp":"+[](std::string n)->std::unique_ptr<::mc::Player>{...}"}]
    }
  ],
  "functions": [
    {"scriptName": "describe", "cpp": "+[](::mc::Entity& e)->std::string{...}"}
  ]
}
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Dict, List


HEADER = (
    "// AUTO-GENERATED by tools/autobind/autobind.py - DO NOT EDIT.\n"
    "// Regenerate from the JSON spec instead of modifying this file.\n"
)


class SpecError(Exception):
    """Raised when the input specification is invalid."""


def topo_sort_classes(classes: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Order classes so that every base precedes its derived classes."""
    by_name = {c["scriptName"]: c for c in classes}
    for c in classes:
        base = c.get("base")
        if base is not None and base not in by_name:
            raise SpecError(
                f"class '{c['scriptName']}' derives from unknown base '{base}' "
                "(the base must be declared in the same spec)"
            )

    ordered: List[Dict[str, Any]] = []
    visiting: set[str] = set()
    done: set[str] = set()

    def visit(name: str) -> None:
        if name in done:
            return
        if name in visiting:
            raise SpecError(f"inheritance cycle detected at class '{name}'")
        visiting.add(name)
        node = by_name[name]
        base = node.get("base")
        if base is not None:
            visit(base)
        visiting.discard(name)
        done.add(name)
        ordered.append(node)

    for c in classes:
        visit(c["scriptName"])
    return ordered


def require_str(obj: Dict[str, Any], key: str, where: str) -> str:
    value = obj.get(key)
    if not isinstance(value, str) or not value:
        raise SpecError(f"{where}: missing or empty string field '{key}'")
    return value


def emit_class(out: List[str], cls: Dict[str, Any]) -> None:
    script_name = require_str(cls, "scriptName", "class")
    cpp_type = require_str(cls, "cppType", f"class '{script_name}'")
    base = cls.get("base")

    out.append(f"    // -- {script_name}" + (f" : {base}" if base else "") + " " + "-" * 20)
    if base:
        base_cpp = None
        # base cppType is resolved by the caller through the class map; placeholder
        out.append(f"    ClassBinder::registerClass<{cpp_type}, {{BASE_CPP}}>(engine, \"{script_name}\");")
    else:
        out.append(f"    ClassBinder::registerClass<{cpp_type}>(engine, \"{script_name}\");")

    for method in cls.get("methods", []):
        name = require_str(method, "scriptName", f"{script_name}.methods")
        cpp = require_str(method, "cpp", f"{script_name}.method '{name}'")
        out.append(f"    ClassBinder::method<{cpp_type}>(engine, \"{name}\", {cpp});")

    for prop in cls.get("properties", []):
        name = require_str(prop, "scriptName", f"{script_name}.properties")
        field = prop.get("field")
        if field:
            # data member bound directly as a read/write accessor
            out.append(f"    ClassBinder::property<{cpp_type}>(engine, \"{name}\", {field});")
            continue
        getter = require_str(prop, "get", f"{script_name}.property '{name}'")
        setter = prop.get("set")
        if setter:
            out.append(f"    ClassBinder::property<{cpp_type}>(engine, \"{name}\", {getter}, {setter});")
        else:
            out.append(f"    ClassBinder::property<{cpp_type}>(engine, \"{name}\", {getter});")

    for static_method in cls.get("staticMethods", []):
        name = require_str(static_method, "scriptName", f"{script_name}.staticMethods")
        cpp = require_str(static_method, "cpp", f"{script_name}.staticMethod '{name}'")
        out.append(f"    ClassBinder::staticMethod<{cpp_type}>(engine, \"{name}\", {cpp});")

    if cls.get("constructible"):
        factory = cls.get("constructor") or f"+[]() -> {cpp_type}* {{ return new {cpp_type}(); }}"
        out.append(f"    ClassBinder::constructor<{cpp_type}>(engine, {factory});")

    out.append(f"    ClassBinder::expose<{cpp_type}>(engine, ns.handle(), \"{script_name}\");")
    out.append("")


def generate_cpp(spec: Dict[str, Any]) -> str:
    namespace = require_str(spec, "namespace", "spec")
    function_name = spec.get("functionName") or f"bindGenerated{namespace.capitalize()}Api"
    includes = spec.get("includes", [])
    classes = spec.get("classes", [])
    functions = spec.get("functions", [])

    cpp_type_by_script_name = {c["scriptName"]: require_str(c, "cppType", "class") for c in classes}
    ordered = topo_sort_classes(classes)

    out: List[str] = [HEADER, ""]
    out.append("#include <memory>")
    out.append("#include <string>")
    out.append("#include <utility>")
    out.append("#include <vector>")
    out.append("")
    for inc in includes:
        out.append(f"#include \"{inc}\"" if not inc.startswith("<") else f"#include {inc}")
    out.append('#include "script/Local.h"')
    out.append('#include "script/ScriptEngine.h"')
    out.append('#include "script/bind/Bind.h"')
    out.append("")

    # Native-class trait declarations must live at global scope.
    for cls in ordered:
        out.append(f"LS_NATIVE_CLASS({cls['cppType']})")
    out.append("")

    out.append("namespace ls::native::generated {")
    out.append("")
    out.append("using ls::script::ClassBinder;")
    out.append("using ls::script::getGlobal;")
    out.append("using ls::script::Local;")
    out.append("using ls::script::makeFunction;")
    out.append("using ls::script::makeNativeFunction;")
    out.append("using ls::script::makeObject;")
    out.append("using ls::script::Object;")
    out.append("using ls::script::ScriptEngine;")
    out.append("using ls::script::Value;")
    out.append("")
    out.append(f"void {function_name}(ScriptEngine& engine) {{")
    out.append("    Local<Object> global = getGlobal(engine);")
    out.append("    // Merge into an existing namespace object when present, so generated")
    out.append("    // bindings compose with hand-written ones (LL-style API layout) instead of")
    out.append("    // clobbering them.")
    out.append(f"    Local<Value>  existingNs = global.getProperty(\"{namespace}\");")
    out.append("    Local<Object> ns = existingNs.isObject() ? Local<Object>(existingNs) : makeObject(engine);")
    out.append("")

    for cls in ordered:
        # Resolve the {BASE_CPP} placeholder now that the map is known.
        start = len(out)
        emit_class(out, cls)
        base = cls.get("base")
        if base:
            base_cpp = cpp_type_by_script_name[base]
            for i in range(start, len(out)):
                out[i] = out[i].replace("{BASE_CPP}", base_cpp)

    if functions:
        out.append("    // -- free functions " + "-" * 20)
        for fn in functions:
            name = require_str(fn, "scriptName", "functions")
            cpp = require_str(fn, "cpp", f"function '{name}'")
            out.append(f"    ns.setProperty(\"{name}\", makeFunction(engine, makeNativeFunction({cpp})));")
        out.append("")

    out.append(f"    global.setProperty(\"{namespace}\", ns);")
    out.append("}")
    out.append("")
    out.append("} // namespace ls::native::generated")
    out.append("")
    return "\n".join(out)


def build_expected(spec: Dict[str, Any]) -> Dict[str, Any]:
    """Produce an expected API-surface fragment (same shape as exportApiSurface)
    so the validator can check the running engine against this spec."""
    namespace = require_str(spec, "namespace", "spec")
    members: Dict[str, Any] = {}
    for cls in spec.get("classes", []):
        entry: Dict[str, Any] = {"type": "class"}
        entry["methods"] = sorted({m["scriptName"] for m in cls.get("methods", [])})
        entry["staticMethods"] = sorted({s["scriptName"] for s in cls.get("staticMethods", [])})
        if cls.get("base"):
            entry["extends"] = cls["base"]
        members[cls["scriptName"]] = entry
    for fn in spec.get("functions", []):
        members[fn["scriptName"]] = {"type": "function"}
    return {namespace: {"type": "object", "members": members}}


def _ts_params(entry: Dict[str, Any]) -> str:
    return ", ".join(f"{p['name']}: {p['type']}" for p in entry.get("tsParams", []))


def build_dts(spec: Dict[str, Any]) -> str:
    """Emit a TypeScript declaration for the bound namespace.

    Uses the `tsParams` / `tsReturns` / `tsType` annotations that parse_headers.py
    records; a hand-written spec without them falls back to `any`.
    """
    namespace = require_str(spec, "namespace", "spec")
    out: List[str] = [
        "// AUTO-GENERATED by tools/autobind - DO NOT EDIT.",
        "",
        f"declare namespace {namespace} {{",
    ]
    for cls in spec.get("classes", []):
        base = f" extends {cls['base']}" if cls.get("base") else ""
        out.append(f"    class {cls['scriptName']}{base} {{")
        if cls.get("constructible"):
            ctor_params = cls.get("tsConstructorParams") or []
            params = ", ".join(f"{p['name']}: {p['type']}" for p in ctor_params)
            out.append(f"        constructor({params});")
        for method in cls.get("methods", []):
            out.append(f"        {method['scriptName']}({_ts_params(method)}): {method.get('tsReturns', 'any')};")
        for static_method in cls.get("staticMethods", []):
            out.append(
                f"        static {static_method['scriptName']}({_ts_params(static_method)}): "
                f"{static_method.get('tsReturns', 'any')};"
            )
        for prop in cls.get("properties", []):
            out.append(f"        {prop['scriptName']}: {prop.get('tsType', 'any')};")
        out.append("    }")
    for fn in spec.get("functions", []):
        out.append(f"    function {fn['scriptName']}({_ts_params(fn)}): {fn.get('tsReturns', 'any')};")
    out.append("}")
    return "\n".join(out) + "\n"


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description="LeviScript auto-binding generator")
    parser.add_argument("spec", help="path to the JSON binding specification")
    parser.add_argument("-o", "--output", required=True, help="path of the generated .cpp/.h")
    parser.add_argument("--emit-expected", help="also write an expected API surface JSON for the validator")
    parser.add_argument("--dts", help="also write a TypeScript declaration (.d.ts) for the bound namespace")
    args = parser.parse_args(argv)

    try:
        with open(args.spec, "r", encoding="utf-8-sig") as handle:
            spec = json.load(handle)
        source = generate_cpp(spec)
    except SpecError as exc:
        print(f"spec error: {exc}", file=sys.stderr)
        return 2
    except (OSError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(source)
    print(f"generated {args.output}")

    if args.emit_expected:
        expected = build_expected(spec)
        with open(args.emit_expected, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(expected, handle, indent=2, ensure_ascii=False)
            handle.write("\n")
        print(f"generated {args.emit_expected}")

    if args.dts:
        with open(args.dts, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(build_dts(spec))
        print(f"generated {args.dts}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
